version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
      -
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv:/csv
    command: >
      sh -c "psql -U postgres -c \"CREATE DATABASE ${POSTGRES_DB};\"" &&
      psql postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB} &&
      CREATE TABLE customer(customer_id int PRIMARY KEY, home_store int, customer_first_name text, customer_email text, customer_since DATE, loyalty_card_number TEXT, birthdate DATE, gender text, birth_year int); &&
      \copy customer from ./csv/customer.csv delimiter ',' CSV HEADER
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
