version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
