version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - ./csv:/csv
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - mynetwork

networks:
  mynetwork:
