[tool.poetry]
name = "databreatheassignment"
version = "0.1.0"
description = "FastApi App"
authors = ["Ivaylo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
